### ISSUE TITLE
 Invalid or incomplete multibyte or wide character

### ISSUE THREAD

**Issue by duerrp** [Vifon/deer#10]
Hi,

Thanks for publishing deer, love the idea of having a lightweight ranger integrated in my zsh environment. Unfortunately, however, I get "Invalid or incomplete multibyte or wide character" warnings in directories with Japanese character file / folder names. Do you have any idea how to suppress this?

Thanks

**Comment by Vifon** [comment]
Strange. Must be a regression. Currently I don't have the access to my PC, but I'll take a look at it ASAP.

**Comment by Vifon** [comment]
I've just checked on a file named ` 日本国` (the first Japanese word I could find: "Japan") and it works without any warnings. What GNU/Linux distribution do you use? Maybe it's a different implementation of some tool deer is using.

**Comment by duerrp** [comment]
I am using ubuntu 14.04, but I just tried to reproduce the problem in a docker container and could not. It must be some particular filename on my machine... I'll let you know if I find it.

Sorry for the trouble.

**Comment by duerrp** [comment]
Actually it turned out not to be a Japanese filename, but a filename with invalid encoding. Deleting the file solved the issue for me...

**Comment by Vifon** [comment]
Yeah, that was what I suspected. Do you consider it something that should be fixed on the deer's side or should we close this issue?

**Comment by Vifon** [comment]
I've managed to reproduce your error. It seems harmless so I've just silenced it.

**Comment by duerrp** [comment]
Thank you very much!
