### ISSUE TITLE
Cannot load `deer`

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Vifon/deer#11]
So, I can't even get Zsh to *source* deer. I even tried changing it to executable, but no such look.

    > ls -lAFh deer
    -rwxr-xr-x  1 ec  staff    13K Oct 18 15:01 deer*
    > source ./deer
    > echo $?
    1

There's no error of any sort; I tried installing `zshdb` and running it on `./deer`, but that's got no output of any sort, either. I'm not a Zsh master, and my configuration isn't very complex … but I get the same error under `zsh -f`, so it's not that either.

(I'm running Zsh 5.1.1.)

**Comment by Vifon** [comment]
You're right, `source deer` returns 1. That shouldn't cause any problems (unless you're running `zsh -e`) but still should be fixed. Thanks.

Calling this:
```zsh
zle -N deer-launch
bindkey '\ek' deer-launch
```
...should still work as usual. Have you tried it?

**Comment by Vifon** [comment]
Ok, should be fixed now thanks to tehora.

**Comment by ELLIOTTCABLE** [comment]
Oh; this was one of those weird perfect-storms of X/Y problems.

1. The original problem is that `esc-k` wasn't working to invoke deer; it for some reason loads the previous item in the history instead,
2. I tried to invoke `deer`, to make sure it'd at least *installed* correctly, even if it wasn't running, and that failed; it wasn't documented anywhere that `deer-launch` was the actual name (also, why *can't* that be directly invoked? Having a hotkey is useful; but it might be nice to just invoke `deer` as a normal program sometimes.)
3. so my first go-to was to check permissions on the binary, which it turns out, was non-executable. (I didn't realize this was irrelevant, heh.)

So, I'm back to where I started:

![](http://ell.io/i1iaPk+)

The start and the end are both me just hitting `esc-k` over and over; as you can see, it just fills in the last command in the history, even when unbound (at the start.) No idea why that's happening. o_O

**Comment by Vifon** [comment]
> why can't that be directly invoked? Having a hotkey is useful; but it might be nice to just invoke deer as a normal program sometimes

deer is implemented as a zle (zsh line editor) widget and heavily uses zle functions. It must be called as a zle widget. You may invoke it with <kbd>alt+x</kbd> which allows you to call a zle widget by name.

Let me explain why it's called `deer-launch` when you source it. The recommended way of loading is using `autoload`. `autoload` treats the whole file as a function named just as the file itself (`deer` in this case). This function calls `deer-launch` if it is called from zle (see the last lines of deer). If you load it manually via `source`, you do not get the toplevel `deer` function but may still use the underlying `deer-launch` function. It should be possible to conditionally create the `deer` function so it will be consistent. I'll do it in a few minutes.

As for the original problem... Did you try with some other keys? Your terminal emulator may be blocking <kbd>alt+k</kbd>. It's the most likely cause.

**Comment by ELLIOTTCABLE** [comment]
Oh, I see! Re: the autoloading, that makes sense. (If you can *easily* simply re-define `deer` within `deer` when autoloaded, that's probably ideal; `keybind <blah> deer` is probably more straight-forward than `keybind <blah> deer-launch`, no?)

I'll dig more into the failure when I get home. For reference, that machine is running OS X El Capitan; and it doesn't look like El Capitan's Terminal.app is using `esc-k` in any way … but that *does* seem like the most likely situation. (If so, a note on that might be worthwhile in the README? A lot of us Mac users out there. ;)

**Comment by Vifon** [comment]
I've already added the additional `deer` wrapper function. See the latest commit: c995ccd.

If you can confirm that it's the issue with Terminal.app, I'll surely add it. :)

**Comment by ELLIOTTCABLE** [comment]
Wow, I was being an idiot. It's not Terminal.app; it's Zsh's own vi-mode. One of the default suggestions for vi-mode (and of course it makes a lot of sense) is to set `KEYTIMEOUT=1`. With that set, `\ek` isn't getting triggered at all; it's `\e` kicking out to `vicmd`, and then `[vicmd] k` causing `history-substring-search-up`. (Might want to mention *that* in the README, for sure. Or even ship with a `vicmd` binding.)

Since `K` (`⇧K`) is unbound, both in Zsh vi-mode and vim itself, I bound that instead. Seems to work fine!
