### ISSUE TITLE
python2 not available

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Vifon/deer#13]
`deer` seems to require a Python installation specifically named `python2`:

    deer-get-relative:4: command not found: python2

On OS X, the default Python install (2.7.10 as of El Capitan) is not version-suffixed (that is, the binary is just `python`), and there's no symlink. Homebrew installs a suffixed `python3`, but is also ignored.

Perhaps have it fall-back to simply `python`, if `python2` is unavailable?

**Comment by Vifon** [comment]
I have an even better idea. It was fairly easy to make it work with both Python 2 and Python 3. Thanks for the report.

**Comment by ELLIOTTCABLE** [comment]
:dart:
