### ISSUE TITLE
'deer' not being sourced when used with 'antigen bundle'

### ISSUE THREAD

**Issue by jonboiser** [Vifon/deer#20]
Is it because deer doesn't have the '.sh' file extension?

I added the lines in the antigen setup to my .zshrc, but couldn't bring up deer. If I manually source deer after the fact (omething like `source ~/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Vifon-SLASH-deer.git/deer`), then it works.

Following other antigen bundles, I simply `cp deer deer.sh` inside the antigen repo folder for deer. After that, everything seemed to work. Maybe antigen looks for '.sh' extensions when it is loading everything.

**Comment by Vifon** [comment]
I'm not familiar with antigen but it seems @hugoh got deer working with it: https://github.com/Vifon/deer/pull/18#issuecomment-218059994

Is this solution suitable for you? I'll probably consider renaming the main file to `deer.sh` in the future though, to avoid confusion.

**Comment by jonboiser** [comment]
That was what I tried originally. The antigen docs show that you can do `antigen bundle [repo] [loc]`, but it seems like `loc` might need to be a directory. So possibly if you do `antigen bundle Vifon/deer deer`, it is looking for `.sh` files under `./deer`. That's my hunch, at least.

**Comment by jonboiser** [comment]
Yeah, so I changed it back to `antigen bundle Vifon/deer deer`, which didn't work. I then moved my `deer.sh` to `./deer` sub-folder, which worked.

**Comment by Vifon** [comment]
Ok then, no point in keeping the old name. Please check if it's working now.

**Comment by jonboiser** [comment]
Yeah, works great! I think my assumptions about antigen were wrong, though. If I do this,

```diff
-antigen bundle Vifon/deer deer
+antigen bundle Vifon/deer
```
I can bring up deer, but none of the movement keys work except 'h'.

**Comment by Vifon** [comment]
I've learned that antigen (and zgen which I've just started using) modifies the `$path` so the command may be autoloaded. I've reverted the rename and added an extra line needed to README. Does it make sense to you, @jonboiser? I'm late to the whole plugin manager party so I'd like to be sure I got it right.

**Comment by jonboiser** [comment]
Yeah, just tried it out with this change
```diff
- antigen bundle Vifon/deer deer
+ antigen bundle Vifon/deer
antigen apply
+autoload -U deer
zle -N deer
bindkey '\ek' deer
```
And it still seems to work fine.
