### ISSUE TITLE
rifle closes shell (at least when previewing a text file)

### ISSUE THREAD

**Issue by rpglover64** [Vifon/deer#22]
Pressing <kbd>r</kbd> (using the default key bindings) on a text file outputs "Vim: Warning: Input is not from a terminal" before opening the file. Typing <kbd>:q</kbd> quits not only vim but also the terminal.

**Comment by Vifon** [comment]
zle (zsh line editor) is quite limited. It seems vim doesn't like being launched from zle. Not much I can do about it. You can configure rifle to launch vim in a new terminal but I'm aware it's an ugly workaround. Sorry.
