### ISSUE TITLE
not worked well with tmux? 

### ISSUE THREAD

**Issue by jinleileiking** [Vifon/deer#28]

**Comment by Vifon** [comment]
It works fine for me in tmux. What's the exact issue?

**Comment by jinleileiking** [comment]
https://github.com/jinleileiking/DotFiles/blob/master/.zshrc

here is my zshrc. alt k not worked well

**Comment by jinleileiking** [comment]
got it I will try

**Comment by jinleileiking** [comment]
I will try it later.

**Comment by jinleileiking** [comment]
closed for now. reopen when I find it
