### ISSUE TITLE
Default keybindings don't work

### ISSUE THREAD

**Issue by justmytwospence** [Vifon/deer#9]
After activating deer, only the `/` and `k` keybindings seem to work for me. Any idea how to troubleshoot this?

**Comment by Vifon** [comment]
Do you know if it was happening before the recent update? Could you paste the output of `setopt`?

**Comment by justmytwospence** [comment]
This is the first time I've tried it, so I'm not sure if its a new 
version thing. Here is my setopt output:

```shell
alwaystoend
autocd
autopushd
nocaseglob
cdablevars
completeinword
extendedhistory
noflowcontrol
globdots
histexpiredupsfirst
histignoredups
histignorespace
histverify
incappendhistory
interactive
login
longlistjobs
monitor
numericglobsort
promptsubst
pushdignoredups
pushdminus
rcexpandparam
rmstarwait
sharehistory
shinstdin
zle
```

**Comment by Vifon** [comment]
I've just tried setting my zsh options the same as you have and deer still works. How did you install deer? Maybe something is missing? Is deer launching at all?

**Comment by justmytwospence** [comment]
I think this was because I was calling bindkey -v after loading deer. Calling it beforehand makes this work.

**Comment by Vifon** [comment]
It makes sense, `bindkey -v` overwrites all the current keys. Thanks for the update.
